### ISSUE TITLE
Latest version of `seaborn` throws an error when generating barplots

### ISSUE THREAD

**Issue by degleris1** [PyPSA/pypsa-usa#108]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

`sns.barplot` throws an error:

```python
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

I tried changing line 286 of `plot_results.py` from:

```python
colors = n.carriers.set_index("nice_name").color[production.columns].values
```

to
```
colors = n.carriers.set_index("nice_name").color[production.columns].values
```

but hit a different error:
```
AttributeError: Rectangle.set() got an unexpected keyword argument 'left'
```

### Solution

`conda list seaborn` gave:

```
# packages in environment at /Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2:
#
# Name                    Version                   Build  Channel
seaborn                   0.13.0               hd8ed1ab_0    conda-forge
seaborn-base              0.13.0             pyhd8ed1ab_0    conda-forge
```

Downgrading to `conda install seaborn=0.12.2` resolved the issue.

@ktehranchi @trevorb1 Would it be reasonable to pin the dependency versions in `environment.yaml` to whatever you two have in your current environments? This way, when anyone installs the environment, they get exactly the same environment you two are using for development. The only downside is that you'll have to unfreeze the environment, update, and freeze again each time you want to update the dependencies.

### Error Message

```shell
s1 = sns.barplot(y="carrier", x="CAPEX", data=costs, alpha=0.6, ax=ax, palette=colors)
Traceback (most recent call last):
  File "/Users/degleris/pypsa-usa/workflow/.snakemake/scripts/tmpis70guwm.plot_results.py", line 370, in <module>
    s1 = sns.barplot(y="carrier", x="CAPEX", data=costs, alpha=0.6, ax=ax, palette=colors)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/lib/python3.11/site-packages/seaborn/categorical.py", line 2355, in barplot
    p.map_hue(palette=palette, order=hue_order, norm=hue_norm, saturation=saturation)
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/lib/python3.11/site-packages/seaborn/_base.py", line 838, in map_hue
    mapping = HueMapping(self, palette, order, norm, saturation)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/lib/python3.11/site-packages/seaborn/_base.py", line 128, in __init__
    map_type = self.infer_map_type(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/lib/python3.11/site-packages/seaborn/_base.py", line 207, in infer_map_type
    if palette in QUAL_PALETTES:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/lib/python3.11/site-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[Wed Oct 18 10:01:44 2023]
Error in rule plot_figures:
    jobid: 1
    input: results/western/networks/elec_s_60_ec_lvopt_Co2L0.75.nc, resources/western/regions_onshore_s_60.geojson, resources/western/regions_offshore_s_60.geojson
    output: results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_capacity_map_base.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_capacity_map_optimized.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_capacity_bar.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_operation_map.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_operation_bar.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_operation_area.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_cost_bar.pdf

RuleException:
CalledProcessError in file /Users/degleris/pypsa-usa/workflow/Snakefile, line 614:
Command 'set -euo pipefail;  /Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/bin/python3.11 /Users/degleris/pypsa-usa/workflow/.snakemake/scripts/tmpis70guwm.plot_results.py' returned non-zero exit status 1.
  File "/Users/degleris/pypsa-usa/workflow/Snakefile", line 614, in __rule_plot_figures
  File "/Users/degleris/.julia/conda/3/x86_64/envs/pypsa-usa2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job plot_figures since they might be corrupted:
results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_capacity_map_base.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_capacity_map_optimized.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_capacity_bar.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_operation_map.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_operation_bar.pdf, results/western/figures/elec_s_60_ec_lvopt_Co2L0.75_operation_area.pdf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```
```


### Anything else?

_No response_

**Comment by ktehranchi** [comment]
Good idea- I will pin dependencies with this PR #109
