### ISSUE TITLE
Getting error while running the workflow

### ISSUE THREAD

**Issue by nomineb** [PyPSA/pypsa-usa#131]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Running into an issue

### Steps To Reproduce

1. snakemake -j4
2. default config file

### Expected Behavior

Error in retrieve_WECC_forecast_data rule, workflow fails after "1 of 21 steps done."

### Error Message

```shell
Traceback (most recent call last):
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmphth_ymke.retrieve_forecast_data.py", line 84, in <module>
    download_wecc_forecasts(URL_WECC_2032, adspath_zips, 2032)
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmphth_ymke.retrieve_forecast_data.py", line 34, in download_wecc_forecasts
    z = zipfile.ZipFile(io.BytesIO(r.content))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
 25% (25 of 100) |#####                  | Elapsed Time: 0:00:01 ETA:   0:00:03[Sun Nov 26 11:14:53 2023]
Error in rule retrieve_WECC_forecast_data:
    jobid: 19
    output: data/WECC_ADS/downloads/2032/Public Data/Hourly Profiles in CSV format, data/WECC_ADS/downloads/2030/WECC 2030 ADS PCM 2020-12-16 (V1.5) Public Data/CSV Shape Files, data/WECC_ADS/processed
    log: logs/retrieve/retrieve_WECC_forecast_data.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/Snakefile, line 157:
Command 'set -euo pipefail;  /Users/nomio/miniforge3/envs/pypsa-usa/bin/python3.11 /Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmphth_ymke.retrieve_forecast_data.py' returned non-zero exit status 1.
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/Snakefile", line 157, in __rule_retrieve_WECC_forecast_data
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/concurrent/futures/thread.py", line 58, in run
  0% (0 of 100) |                        | Elapsed Time: 0:00:01 ETA:  --:--:--EIA930_BALANCE_2023_Jan_Jun.csv downloaded successfully
100% (100 of 100) |######################| Elapsed Time: 0:00:04 Time:  0:00:04
```
```


### Anything else?

_No response_

**Comment by ktehranchi** [comment]
@nomineb Give it a go now- this should work.
