### ISSUE TITLE
Mutli-Horizon fails for only subset of the year

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#333]
### Checklist

- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### Issue exisits on what branch

Develop

### The Issue

If I run a muti-horizon model, but for only a subset of the year (ie. Jan and Feb) the workflow fails (I do acknowledge this is kinda an odd thing to run, haha) 

### Steps To Reproduce

Put this in the config file 
```yaml
# docs :
scenario:
  interconnect: ["western"] #"usa|texas|western|eastern"
  clusters: [80]
  opts: [Ep-Co2L0.2]
  ll: [v1.0]
  scope: "total" # "urban", "rural", or "total"
  sector: "" # G
  planning_horizons:
  - 2030
  - 2050 #(2030, 2040, 2050)

foresight:  # Only Single Stage Currently

# docs :
enable:
  build_cutout: false

snapshots:
  start: "2019-01-01"
  end: "2019-03-01"
  inclusive: "left"
```

### Error Message

```shell
INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, links, loads, storage_units
Traceback (most recent call last):
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmp7xtms1lm.cluster_network.py", line 512, in <module>
    n.snapshot_weightings.loc[n.investment_periods[0]].objective.sum() / 8760.0
                              ~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
           ^^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size
```

**Comment by trevorb1** [comment]
Oh, this is failing with only a single horizon as well

**Comment by trevorb1** [comment]
hmm... investment periods is not being assigned higher up in the workflow 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/880a4460-85e7-4387-8b2c-e6c3e20a258c)

**Comment by trevorb1** [comment]
Its assigned correctly at the start and when writing out in `add_electricity`

**Comment by ktehranchi** [comment]
Sorry I noticed this and made fixes on my branch
 add this beneath 458 in cluster
```

    n = pypsa.Network(snakemake.input.network)
    n.set_investment_periods( 
        periods=snakemake.params.planning_horizons,
    )
```

**Comment by ktehranchi** [comment]
during simplify network the investment periods get dropped. I didn't look into the cause more, but it could be a bug in pypsa

**Comment by trevorb1** [comment]
Error is in Simplify Network 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/9a07be90-ecfd-4af6-80da-2564ac54b58e)

**Comment by trevorb1** [comment]
Reported to PyPSA [here](https://github.com/PyPSA/PyPSA/issues/890)
