### ISSUE TITLE
Cost retrieval for years before 2022

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#408]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

If doing a validation run, the user will set the investment period to a historical year. With PR #392, we retrieve the latest ATB from PUDL, which does not include years previous to 2022. A error is thrown in this case. 

### Steps To Reproduce

1. Set investment period to 2020
2. Run the workflow

### Expected Behavior

It may make sense to check if the investment period is earlier than 2022 when retrieving the cost data. If it is, just print a warning and retrieve the 2022 data anyways. 2021 data also may be available, but I havent explicitly checked that. 

### Error Message

```shell
Traceback (most recent call last):
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpqmbrfsk8.build_cost_data.py", line 385, in <module>
    [
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpqmbrfsk8.build_cost_data.py", line 389, in <listcomp>
    "value": aeo.loc[aeo["pypsa-name"] == source_name, "value"].values[0],
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by trevorb1** [comment]
There is an issue with `offshore_floating` when using investment years earlier than 2024 as well. Gives the following error. If doing a future year (ie. 2030), everything runs fine. This error comes up regardless if `offshore_wind` is a carrier included or not

```
Traceback (most recent call last):
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpsbvln9yl.add_electricity.py", line 1000, in <module>
    main(snakemake)
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpsbvln9yl.add_electricity.py", line 853, in main
    attach_conventional_generators(
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpsbvln9yl.add_electricity.py", line 382, in attach_conventional_generators
    add_co2_emissions(n, costs, carriers)
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpsbvln9yl.add_electricity.py", line 125, in add_co2_emissions
    n.carriers.loc[carriers, "co2_emissions"] = costs.co2_emissions[suptechs].values
                                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/series.py", line 1153, in __getitem__
    return self._get_with(key)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/series.py", line 1194, in _get_with
    return self.loc[key]
           ~~~~~~~~^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexing.py", line 1420, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexing.py", line 1360, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexing.py", line 1558, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/trevor/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['offwind_floating'] not in index"
```
