### ISSUE TITLE
Can not meet generation constraint for `WA BC gas trade` constrinat. 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#487]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

The capacity of the pipeline connecting WA to BC is not large enough to meet the export constraint. Im guessing this may be due to BC connecting to multiple states, and we are accidentally summing the exports over multiple states, rather than individual. But this is just a guess. 

### Error Message

```shell
ng_limit_export_min-2018-WA BC gas trade: +3 Link-p[(2018, Timestamp('2018-01-01 00:00:00')), WA BC gas trade] + 3 Link-p[(2018, Timestamp('2018-01-01 03:00:00')), WA BC gas trade] + 3 Link-p[(2018, Timestamp('2018-01-01 06:00:00')), WA BC gas trade] ... +3 Link-p[(2018, Timestamp('2018-12-31 15:00:00')), WA BC gas trade] + 3 Link-p[(2018, Timestamp('2018-12-31 18:00:00')), WA BC gas trade] + 3 Link-p[(2018, Timestamp('2018-12-31 21:00:00')), WA BC gas trade] ≥ 6246940.5
Traceback (most recent call last):
  File "/home/trevor/master/pypsa-usa/workflow/.snakemake/scripts/tmpafz715li.solve_network.py", line 1473, in <module>
    n = solve_network(
        ^^^^^^^^^^^^^^
  File "/home/trevor/master/pypsa-usa/workflow/.snakemake/scripts/tmpafz715li.solve_network.py", line 1421, in solve_network
    raise RuntimeError("Solving status 'infeasible'")
RuntimeError: Solving status 'infeasible'
```

**Comment by trevorb1** [comment]
Ugh. This is annoying as its a data issue.

- The [USA state-to-state capacity dataset](https://www.eia.gov/naturalgas/data.php#pipelines) states that in 2019 the pipeline capacity from Washington to British Columbia is 51 MMCFD (line 15604 in "Pipeline State2State Capacity" sheet)

- On the EIA Natural Gas movement by state webpage for [Washington](https://www.eia.gov/dnav/ng/ng_move_ist_a2dcu_SWA_a.htm), it states that the movement from Washington to BC in 2019 was 22870 MMCF

- However, based on the capacity of the pipeline, this should not be possible.
  - 51 MMCFD x 365Days = 18615 MMCF

**Comment by ktehranchi** [comment]
you should email the EIA about this, they usually respond very quickly

**Comment by trevorb1** [comment]
I guess the solution is to generate a second dataset based on trade flows to find currently installed capacity. Then merge that with the EIA provided dataset that gives capacity, taking the larger value between the two datasets. 

Seems like this situation is just an edge case, as the WA -> BC pipeline is the only one experiencing this issue in Western and Texas interconnect for 2019. But I guess this issue may pop up for a different year/interconnect.
